<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Traits\ApiResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Response;
use Wordvel\Data\EditorPreviewRequestData;
use Wordvel\Data\EditorPreviewResource;
use Wordvel\Editor\EditorPreviewRepository;

final class WordvelEditorPreviewController
{
    use ApiResponse;

    public function __construct(
        private readonly EditorPreviewRepository $previews,
    ) {}

    /**
     * @OA\Post(
     *     path="/api/wordvel/editor-preview",
     *     summary="Sync WordVel editor previews",
     *     description="Receives React-rendered placeholder HTML and CSS generated by the WordVel React library. Laravel stores the artifact so WordPress can render Gutenberg previews that match the actual site components.",
     *     tags={"WordVel"},
     *     @OA\RequestBody(required=true, @OA\JsonContent(ref="#/components/schemas/EditorPreviewRequestData")),
     *     @OA\Response(response="200", description="Preview artifact stored", @OA\JsonContent(ref="#/components/schemas/EditorPreviewResponse"))
     * )
     */
    public function store(EditorPreviewRequestData $request): JsonResponse
    {
        $this->previews->store($request);

        return $this->resourceResponse(new EditorPreviewResource(
            blocks: count($request->blocks),
            css_bytes: strlen($request->css),
        ));
    }

    /**
     * @OA\Get(
     *     path="/api/wordvel/editor-preview",
     *     summary="Get stored WordVel editor previews",
     *     description="Returns the React-generated placeholder HTML artifact used by WordPress Gutenberg to preview WordVel blocks.",
     *     tags={"WordVel"},
     *     @OA\Response(response="200", description="Stored editor preview artifact")
     * )
     */
    public function show(): JsonResponse
    {
        return $this->resourceResponse($this->previews->preview());
    }

    /**
     * @OA\Get(
     *     path="/api/wordvel/editor.css",
     *     summary="Get stored WordVel editor CSS",
     *     description="Returns the React-generated CSS used by WordPress Gutenberg to make WordVel block previews match the website.",
     *     tags={"WordVel"},
     *     @OA\Response(response="200", description="Stored editor CSS")
     * )
     */
    public function css(): Response
    {
        return response($this->previews->css(), 200, [
            'Content-Type' => 'text/css; charset=UTF-8',
        ]);
    }
}
